### ISSUE TITLE
[Feature request] Optional parameters for write_svg

### ISSUE THREAD

**Issue by richieadler** [ShayHill/svg_ultralight#1]
It would be nice to have the following optional parameters in write_svg:

* **xml_header**: (boolean, default False) to indicate that the XML header would be added to the XML file.
* **encoding**: (default "utf-8") to indicate the output encoding for the file (this may conflict with the xml_header value). It just irks me having an ASCII encoding in the file :)
* **add_doctype** (boolean, default **False**, as currently recommended) to determine whether the DOCTYPE section gets added

Also it would be good to upgrade the version to 1.1 or remove it altogether.

**Comment by ShayHill** [comment]
Thank you for the request. The real question might be, “Why have an xml header EVER?” Inkscape, Python xml parsers, and the subset of browsers I’ve tried don’t need it, certainly they don’t need DOCTYPE. That being said, it appears to be the only way to have a non-ascii encoding.

It feels like you know a lot more about it than I do. I left it in because Inkscape includes it in save files, and it’s safe to assume they know something I don’t.

As you say, there should definitely be an encoding argument or, at least, a hard-coded utf-8. Sending it out otherwise was an oversight.

I’d rather hard-code something workable (if imperfect) than add three more arguments. Which of these makes most sense to you?


  1.  Leave xml(1.1) header and DOCTYPE, add encoding argument with default utf-8. The header and DOCTYPE don’t seem to hurt anything, and a Python user with any sophistication at all will be able to strip three lines off the top of a file.
  2.  Remove xml header and DOCTYPE. This leaves the user with ASCII encoding.
  3.  Leave xml(1.1) header, remove DOCTYPE, add encoding argument with default utf-8. I had a look around, but couldn’t find the current recommendation to remove DOCTYPE. That being said, it removing it doesn’t beak anything that I have available to test.
  4.  1 or 3 and “hard code” utf-8.

What say you, Marcelo?

-Shay

**Comment by richieadler** [comment]
> Thank you for the request. The real question might be, “Why have an xml header EVER?” Inkscape, Python xml parsers, and the subset of browsers I’ve tried don’t need it, certainly they don’t need DOCTYPE. That being said, it appears to be the only way to have a non-ascii encoding.

Huh? What do you mean by that? If in etree.tostring, if you set encoding='utf-8' and xml_declaration=True, you get a nice xml header with the utf-8 encoding, without needing a doctype parameter set. Then you save the returned bytes object as binary, as always. (What's incompatible is setting encoding="unicode" and then xml_declaration=True.)

>. I left it in because Inkscape includes it in save files, and it’s safe to assume they know something I don’t. 

The formal specification uses it, but apparently even the SVG workgroup is recommending to drop the DOCTYPE, even in cases where would be mandatory for XML, like version 1.1 (sadly, the message referenced in the comment I read is in a now dead Yahoo Group: <https://groups.yahoo.com/neo/groups/svg-developers/conversations/topics/48562>)

The header should be optional because when you are creating standalone documents you usually needed, but if you're generating a SVG to be embedded directly into a HTML5 document (as you can), you must omit it.

Also I usually like optional parameters with default values, as described, so you normally have the desired outcome but you can change it. And if a wrong combination makes the underlying library fail, you can document the unacceptable combinations but nothing else. Being optional, the arguments shouldn't encumber the users. (As you can see, I don't agree with your with stance of not adding more arguments...)

>The header and DOCTYPE don’t seem to hurt anything, and a Python user with any sophistication at all will be able to strip three lines off the top of a file. 

We have conflicting intended audiences here. We have users sophisticated enough to trim a XML file (which they shouldn't be dealing with directly anyway), but not sophisticated enough to deal with three additional parameters with default values? Something doesn't add up :)

If we're talking about the realms of possibility, I could monkeypatch write_svg, create my own private branch of svg_ultralight, or drop it altogether and use lxml exclusively, but my intent is helping you make the module more useful for more people (one of them being me, of course).

**Comment by ShayHill** [comment]
Changes from .2 to .3

--------------------------------------------------------------------------------
write_svg now passes **tostring_kwargs directly to lxml.etree.tostring.

def write_svg(
    svg: str,
    xml: etree.Element,
    stylesheet: Optional[str] = None,
    do_link_css: bool = False,
    **tostring_kwargs,
) -> str:

New default is no xml_declaration. Will pass good csv defaults if xml_declaration is True. This can be overridden
With ‘encoding’ and ‘doctype’ kwargs. Default encoding is now UTF-8

--------------------------------------------------------------------------------
nsmap is now an optional argument to `new_svg_root`. Defaults to `svg_ultralight.NSMAP`, so ignore this
argument for previous behavior. The argument is here if you'd like to pass your own namespace map.

--------------------------------------------------------------------------------
new shorthand for creating elements in constructors.new_element

def new_element(tag: str, **params: Union[str, float]) -> etree.Element:

def new_sub_element(
    parent: etree.Element, tag: str, **params: Union[str, float]
) -> etree.Element:

XML version is seemingly hard coded into lxml. I’ll wait for lxml to update. Thank you again for the feedback.

-Shay
